### ISSUE TITLE
'is_admin' not defined on user migration

### ISSUE THREAD

**Issue by hesamzkr** [ndeblauw/hsdemo#3]
Hello, in this [line](https://github.com/ndeblauw/hsdemo/blob/84f9a785a23490355fe8888b7af3174197227cd7/database/seeders/DatabaseSeeder.php#L28) in the seeder 'is_admin' is being set but it's not set in the migrations, is this an issue or laravel magic I don't understand?

**Comment by ndeblauw** [comment]
Hi Hesam, 

The isadmin property was added in a later migration, check this file:
https://github.com/ndeblauw/hsdemo/blob/84f9a785a23490355fe8888b7af3174197227cd7/database/migrations/2023_11_13_112526_add_is_admin_to_users_table.php

**Comment by hesamzkr** [comment]
ah yea I see, thank you
